[project]
name = "slack-ai-chatbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=0.1.0",
    "openai>=1.78.1",
    "python-dotenv==1.1.0",
    "slack-sdk==3.35.0",
    "streamlit>=1.45.1",
    "watchdog==6.0.0",
]
